Update to v3.3.6 for client
portapps/nextcloud-portable pull request #37
Opened 2021-12-17 15:02 UTC by FuzzyMistborn

Think I did this right.

2022-01-07 23:24 UTC, crazy-max requested changes
Yes LGTM, thnaks, can you rebase please?

2022-01-07 23:25 UTC, crazy-max approved these changes

2022-01-07 23:26 UTC, crazy-max commented on build.properties
> +app.release = 16
```suggestion
app.release = 15
```

Actually should be `15`

2022-01-07 23:35 UTC, merged

2022-01-08 02:36 UTC, FuzzyMistborn commented
Yeah I updated the build on my fork and I didn't realize it had updated here.  Thanks for merging (and the useful app!)